version: 2.1

executors:
  aice-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/aicejs

whitelist: &whitelist
  paths:
    - .npmignore
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - CODE_OF_CONDUCT.md
    - LICENSE
    - package.json
    - README.md
    - .babelrc
    - .eslintrc.json
    - yarn.lock

jobs:
  test-and-lint:
    executor: aice-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum \"yarn.lock\" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum \"yarn.lock\" }}
          paths:
            - ~/.cache/yarn
      - run: yarn lint
      - run: yarn coverage
      - run: yarn report-coverage
      - store_artifacts:
          path: ~/aicejs/cov
      - persist_to_workspace:
          root: ~/aicejs
          <<: *whitelist

  deploy:
    executor: aice-executor
    steps:
      - attach_workspace:
          at: ~/aicejs
      - run: 
          name: Compile AIce code
          command: yarn --cwd aice compile
      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish
          command: npm publish -d ./packages/aice/dist
workflows:
  version: 2
  build:
    jobs:
      - test-and-lint
      - deploy:
          requires:
            - test-and-lint
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
