version: 2.1

executors:
  aice-executor:
    docker:
      - image: circleci/node:lts
    working_directory: ~/aicejs

jobs:
  test-lint-build:
    executor: aice-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-dependencies-{{ checksum \"yarn.lock\" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: v1-dependencies-{{ checksum \"yarn.lock\" }}
          paths:
            - ~/.cache/yarn
      - run: yarn bootstrap
      - run: yarn lint
      - run: yarn coverage
      - run: yarn report-coverage
      - run: yarn compile
      - store_artifacts:
          path: ~/aicejs/cov
      - persist_to_workspace:
          root: ~/aicejs
          paths: 
            - packages

  publish-aice:
    executor: aice-executor
    steps:
      - attach_workspace:
          at: ~/aicejs
      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish AIce
          command: npm publish -d ./packages/aice/dist
  publish-aice-cli:
    executor: aice-executor
    steps:
      - attach_workspace:
          at: ~/aicejs
      - run: 
          name: Write NPM Token to ~/.npmrc
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc          
      - run:
          name: Publish AIce-cli
          command: npm publish -d ./packages/aice-cli/lib
workflows:
  version: 2
  build:
    jobs:
      - test-lint-build
#      - publish-aice:
#          requires:
#            - test-lint-build
#          filters:
#            tags:
#              only: /^aice@.*/
#      - publish-aice-cli:
#          requires:
#            - test-lint-build
#          filters:
#            tags:
#              only: /^aice-cli@.*/
